### PR TITLE
Support OSX/Mono #14

### PR DESCRIPTION
**Pull request by yufeih**
- Bundle native dependencies on all platforms to the nuget package.
- Do not ilmerge LibSharp2Git so the native dependencies can be loaded correctly.
- Do not run verpatch.exe on linux and mac

### CODE REVIEW

**Comment by yufeih** [comment]
For https://github.com/Fody/Stamp/issues/14

**Comment by bording** [comment]
Updating which native binaries get included in the package is good, but removing the ILMerge doesn't actually fix the issue I was talking about in #14, unfortunately.
 
If LibGit2Sharp.dll isn't ILMerged, then Fody ends up loading the assembly via its `CurrentDomain_AssemblyResolve()` fallback method, which uses `File.ReadAllBytes()` / `Assembly.Load()`.

Doing that causes the same problem as before on mono: It doesn't have a file path to go looking for the dllmap config file.

Also, `verpatch.exe` is what is actually writing the version number into the output assembly, so not running it on linux/mac means Stamp doesn't actually do anything. To get this working on non-windows platforms, the functionality provided by `verpatch.exe` is going to need to be replaced by something that works cross-platform.

**Comment by yufeih** [comment]
Yeah, removing ilmerge doesn't load the native binary. I happened to include the dylib in the project folder yesterday and thought it worked.

Without running `verpatch.exe`, I am still able to get the expected `AssemblyInformationalVersionAttribute`, that attribute contains all the git hash information and is what this project all about. 

So at least we can to make it work on OSX for the majority who only care about `AssemblyInformationalVersionAttribute` and show a warning about the lack of ability to patch win32 version.

**Comment by qmfrederik** [comment]
Hi,

I think we can bypass the Mono dllmap issue if we use Costura.Fody to load the native assembly instead. Would require patching Costura.Fody so that it loads the correct library (.dll/.so/.dylib) depending on the platform, and embedding the libgit libraries with a consistent name - e.g. always libgit.[dll/so/dylib].

I'll have a look & let you know how it goes

**Comment by SimonCropp** [comment]
replaced by https://github.com/Fody/Stamp/pull/19

**Comment by SimonCropp** [comment]
@qmfrederik would prefer not to use costura inside the msbuild context. messing with assembly loading in that context has cause me pain in the past

**Comment by qmfrederik** [comment]
@SimonCropp In that case, the following should work:
- Include the libgit libraries in Stamp.Fody (either as an embedded resource or just as a file that is included in the NuGet package, probably an embedded resource works best)
- Use `LoadLibrary` (on Windows) or `dlopen` (on Linux) to load the .dll/.so file into the process
- Once the native library is loaded, all the P/Invoke methods should just work

@bording I'm assuming that a calling `dlopen` explicitly would remove the need for `dllmap` on Mono, is this correct?

**Comment by bording** [comment]
@qmfrederik Yes, using `LoadLibrary`/`dlopen` to load the native libraries would bypass the need for the dllmap file. 

 However, for that to work, you'd actually need to make upstream changes to LibGit2Sharp. The `DllImport` attribute and calling `LoadLibrary`/`dlopen` require completely different approaches to get a access to the native methods you want to call.

Alternatively, you could bypass LibGit2Sharp altogether, and just directly use the native libgit2 library yourself, going with the `LoadLibrary`/`dlopen` option. You'd end up reproducing a lot of what LibGit2Sharp already does, though.

**Pull request closed without merging**
